from __future__ import annotations

# Re-exported from xcode.ai.types for consumers that import via xcode.agent.types
from xcode.ai.events import StopReason
from xcode.ai.types import (
    ImageContent,
    StreamOptions,
    TextContent,
    ThinkingContent,
    ThinkingLevel,
    ToolCallContent,
)

from .config import (
    AfterToolCallContext,
    AfterToolCallResult,
    AgentContext,
    AgentLoopConfig,
    AgentLoopMetrics,
    AgentLoopResult,
    AgentLoopTurnUpdate,
    BeforeToolCallContext,
    BeforeToolCallResult,
    CompactInstructions,
    CompactPriority,
    ShouldStopAfterTurnContext,
)
from .events import (
    AgentEndEvent,
    AgentEvent,
    AgentStartEvent,
    CompactionArchive,
    CompactionEvent,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    ThinkingUpdateEvent,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TurnEndEvent,
    TurnStartEvent,
)
from .messages import (
    AgentMessage,
    AssistantMessage,
    BranchSummaryMessage,
    CompactionSummaryMessage,
    SystemMessage,
    ToolResultMessage,
    UserMessage,
)
from .protocols import (
    AgentTool,
    AgentToolResult,
    CancellationSignal,
    ContentBlock,
    QueueMode,
    ToolExecutionMode,
    ToolUpdateCallback,
)

__all__ = [
    "AfterToolCallContext",
    "AfterToolCallResult",
    "AgentContext",
    "AgentEndEvent",
    "AgentEvent",
    "AgentLoopConfig",
    "AgentLoopMetrics",
    "AgentLoopResult",
    "AgentLoopTurnUpdate",
    "AgentMessage",
    "AgentStartEvent",
    "AgentTool",
    "AgentToolResult",
    "AssistantMessage",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "BranchSummaryMessage",
    "CancellationSignal",
    "CompactionArchive",
    "CompactionEvent",
    "CompactInstructions",
    "CompactPriority",
    "CompactionSummaryMessage",
    "ContentBlock",
    "MessageEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "QueueMode",
    "ShouldStopAfterTurnContext",
    "SystemMessage",
    "ThinkingUpdateEvent",
    "ToolExecutionEndEvent",
    "ToolExecutionMode",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "ToolResultMessage",
    "ToolUpdateCallback",
    "TurnEndEvent",
    "TurnStartEvent",
    "UserMessage",
]
