"""审计、权限和钩子能力。

trace 依赖 RAG 类型，使用时从 `observability.tracing` 直接导入，避免聚合
入口和 RAG pipeline 形成循环依赖。
"""

from .audit import AuditLogger, AuditRecord, JsonlAuditLogger, redact_text
from .external_hooks import (
    ExternalHookDiagnostic,
    ExternalHookExecution,
    ExternalHookFailure,
    ExternalHookRunner,
)
from .correlation import (
    EventCorrelation,
    hook_correlation_fields,
    HookCorrelationFields,
    RuntimeCorrelation,
)
from .hooks import (
    BeforeAgentStartEvent,
    BeforeProviderRequestEvent,
    CompactEvent,
    ErrorEvent,
    HarnessEvent,
    HookManager,
    HookRecord,
    PostToolEvent,
    PreToolEvent,
    SignalHookManager,
)

from .permission_model import (
    Action,
    ActionExtractor,
    ApprovalCandidate,
    ApprovalResult,
    BoundaryContext,
    Constraint,
    ExternalDirectory,
    FileGrantStore,
    FingerprintLookupResult,
    GrantRecord,
    InMemoryGrantStore,
    PathBoundaryPolicyEvaluator,
    PolicyEvaluator,
    TargetFingerprint,
    PermissionResolver,
    StaticPermission,
    StaticPolicyEvaluator,
    StructuredBoundaryPolicyEvaluator,
    Target,
    UnresolvedEffect,
    Verdict,
    compute_shadow_approval_candidate,
    create_grant_record,
    evaluate_policy_constraints,
)
from .shell_analyzer import (
    CommandSemanticsRegistry,
    FileEffect,
    PosixAnalyzer,
    PowerShellAnalyzer,
    ShellAnalysis,
    ShellAnalysisPolicyEvaluator,
    analyze_shell_command,
)
from .permissions import (
    HITLResult,
    PermissionApprovalCallback,
    PermissionCheckResult,
    PermissionDecision,
    PermissionEngine,
    PermissionEngineConfig,
    PermissionEngineResult,
    PermissionPolicy,
)

__all__ = [
    "AuditLogger",
    "AuditRecord",
    "Action",
    "ActionExtractor",
    "ApprovalCandidate",
    "ApprovalResult",
    "BeforeAgentStartEvent",
    "BeforeProviderRequestEvent",
    "BoundaryContext",
    "CompactEvent",
    "Constraint",
    "ErrorEvent",
    "ExternalHookDiagnostic",
    "ExternalHookExecution",
    "ExternalHookFailure",
    "ExternalHookRunner",
    "EventCorrelation",
    "hook_correlation_fields",
    "HookCorrelationFields",
    "ExternalDirectory",
    "FileGrantStore",
    "FingerprintLookupResult",
    "GrantRecord",
    "HarnessEvent",
    "HITLResult",
    "HookManager",
    "HookRecord",
    "InMemoryGrantStore",
    "JsonlAuditLogger",
    "PermissionApprovalCallback",
    "PermissionCheckResult",
    "PermissionDecision",
    "PermissionEngine",
    "PermissionEngineConfig",
    "PermissionEngineResult",
    "PermissionPolicy",
    "RuntimeCorrelation",
    "PolicyEvaluator",
    "PermissionResolver",
    "CommandSemanticsRegistry",
    "FileEffect",
    "PathBoundaryPolicyEvaluator",
    "PosixAnalyzer",
    "PowerShellAnalyzer",

    "ShellAnalysis",
    "ShellAnalysisPolicyEvaluator",
    "SignalHookManager",
    "UnresolvedEffect",
    "StaticPermission",
    "PostToolEvent",
    "PreToolEvent",
    "StaticPolicyEvaluator",
    "StructuredBoundaryPolicyEvaluator",
    "Target",
    "TargetFingerprint",
    "analyze_shell_command",
    "Verdict",
    "compute_shadow_approval_candidate",
    "create_grant_record",
    "evaluate_policy_constraints",
    "redact_text",
]
