"""审计、权限和钩子能力。

trace 依赖 RAG 类型，使用时从 `observability.tracing` 直接导入，避免聚合
入口和 RAG pipeline 形成循环依赖。
"""

from .audit import AuditRecord, JsonlAuditLogger, redact_text
from .hooks import (
    BeforeAgentStartEvent,
    BeforeProviderRequestEvent,
    CompactEvent,
    ErrorEvent,
    HarnessEvent,
    HookManager,
    HookRecord,
    PostToolEvent,
    PreToolEvent,
)
from ._safety_backstop import SafetyBackstopPolicyEvaluator
from .permission_model import (
    Action,
    ActionExtractor,
    ApprovalCandidate,
    ApprovalResult,
    BoundaryContext,
    Constraint,
    FileGrantStore,
    FingerprintLookupResult,
    GrantRecord,
    InMemoryGrantStore,
    PolicyEvaluator,
    TargetFingerprint,
    PermissionResolver,
    StaticPolicyEvaluator,
    StructuredBoundaryPolicyEvaluator,
    Target,
    Verdict,
    compute_shadow_approval_candidate,
    create_grant_record,
    evaluate_policy_constraints,
)
from .permissions import (
    HITLResult,
    PermissionApprovalCallback,
    PermissionCheckResult,
    PermissionDecision,
    PermissionEngine,
    PermissionEngineConfig,
    PermissionEngineResult,
    PermissionPolicy,
    PermissionRule,
)

__all__ = [
    "AuditRecord",
    "Action",
    "ActionExtractor",
    "ApprovalCandidate",
    "ApprovalResult",
    "BeforeAgentStartEvent",
    "BeforeProviderRequestEvent",
    "BoundaryContext",
    "CompactEvent",
    "Constraint",
    "ErrorEvent",
    "FileGrantStore",
    "FingerprintLookupResult",
    "GrantRecord",
    "HarnessEvent",
    "HITLResult",
    "HookManager",
    "HookRecord",
    "InMemoryGrantStore",
    "JsonlAuditLogger",
    "PermissionApprovalCallback",
    "PermissionCheckResult",
    "PermissionDecision",
    "PermissionEngine",
    "PermissionEngineConfig",
    "PermissionEngineResult",
    "PermissionPolicy",
    "PolicyEvaluator",
    "PermissionResolver",
    "SafetyBackstopPolicyEvaluator",
    "PermissionRule",
    "PostToolEvent",
    "PreToolEvent",
    "StaticPolicyEvaluator",
    "StructuredBoundaryPolicyEvaluator",
    "Target",
    "TargetFingerprint",
    "Verdict",
    "compute_shadow_approval_candidate",
    "create_grant_record",
    "evaluate_policy_constraints",
    "redact_text",
]
